approve_by_comment: true
<<<<<<< HEAD
approve_regex: \b[aA][pP]+[rR][oO][vV][eE][dD]?\b
reject_regex: \b[rR][eE][jJ][eE][cC][tT]([eE][dD])?\b
reset_on_push: false
reviewers:
  members:
  - bonpixel
  - codetothepoint
  - mhewson
  - OwlbearMedia
  - panganibanpj
  - peripateticus
  - petersgrandadventure
  - rhuded
  name: default
  required: 1
=======
approve_regex: "\\b[aA][pP]+[rR][oO][vV][eE][dD]?\\b"
reject_regex: "\\b[rR][eE][jJ][eE][cC][tT]([eE][dD])?\\b"
reset_on_push: true
reviewers: 
  - 
    conditions: 
      branches: 
        - master
    members: 
      - bonpixel
      - codetothepoint
      - mhewson
      - megafatsquirrel
      - OwlbearMedia
      - panganibanpj
      - peripateticus
      - petersgrandadventure
      - rhuded
    name: default
    required: 1
    
>>>>>>> 58b9fb9cd4c17d9cb6fff5927df69f052c00a721
