approve_by_comment: true
approve_regex: \b[aA][pP]+[rR][oO][vV][eE][dD]?\b
reject_regex: \b[rR][eE][jJ][eE][cC][tT]([eE][dD])?\b
reset_on_push: true
reviewers:
  -
    name: default
    required: 1
    members:
      - bonpixel
      - codetothepoint
      - mhewson
      - OwlbearMedia
      - panganibanpj
      - peripateticus
      - petersgrandadventure
      - rhuded
    conditions:
      branches:
        - master  # only need to approve if merging to master
